// 100 public finance figures, tiered by recognisability (1 = most iconic, 6 = finance-specialist)
// wiki: Wikipedia article title used to fetch headshots via the REST summary API

export const PEOPLE = [
  // ── TIER 1 ── Globally iconic ───────────────────────────────────────────
  { id:  1, name: "Warren Buffett",       firm: "Berkshire Hathaway",          bio: "Oracle of Omaha. World's most celebrated long-term investor.",                           wiki: "Warren_Buffett",                    tier: 1 },
  { id:  2, name: "Elon Musk",            firm: "Tesla / SpaceX / X",          bio: "Built Tesla, SpaceX, and X into multi-hundred-billion-dollar companies.",               wiki: "Elon_Musk",                         tier: 1 },
  { id:  3, name: "Jeff Bezos",           firm: "Amazon",                      bio: "Grew Amazon from a garage into a $2 trillion company.",                                  wiki: "Jeff_Bezos",                        tier: 1 },
  { id:  4, name: "Bill Gates",           firm: "Microsoft / Gates Foundation", bio: "Co-founded Microsoft. World's richest person for two decades.",                        wiki: "Bill_Gates",                        tier: 1 },
  { id:  5, name: "Mark Zuckerberg",      firm: "Meta",                        bio: "Built Facebook into a 3-billion-user social media empire.",                              wiki: "Mark_Zuckerberg",                   tier: 1 },
  { id:  6, name: "Jamie Dimon",          firm: "JPMorgan Chase",              bio: "Longest-serving CEO of a major US bank. Navigated every crisis since 2005.",            wiki: "Jamie_Dimon",                       tier: 1 },
  { id:  7, name: "Larry Fink",           firm: "BlackRock",                   bio: "Runs the world's largest asset manager with over $10T AUM.",                            wiki: "Larry_Fink",                        tier: 1 },
  { id:  8, name: "Ray Dalio",            firm: "Bridgewater Associates",      bio: "Founded the world's largest hedge fund. Author of Principles.",                         wiki: "Ray_Dalio",                         tier: 1 },

  // ── TIER 2 ── Major CEOs and investors ──────────────────────────────────
  { id:  9, name: "George Soros",         firm: "Soros Fund Management",       bio: "Broke the Bank of England. Made $1B in a single 1992 trade.",                          wiki: "George_Soros",                      tier: 2 },
  { id: 10, name: "Michael Bloomberg",    firm: "Bloomberg LP",                bio: "Built a financial data empire. Served three terms as New York City mayor.",             wiki: "Michael_Bloomberg",                 tier: 2 },
  { id: 11, name: "Tim Cook",             firm: "Apple",                       bio: "Took Apple from $300B to $3T market cap as CEO.",                                       wiki: "Tim_Cook",                          tier: 2 },
  { id: 12, name: "Satya Nadella",        firm: "Microsoft",                   bio: "Transformed Microsoft with a cloud-first strategy, tripling its value.",                wiki: "Satya_Nadella",                     tier: 2 },
  { id: 13, name: "Jensen Huang",         firm: "NVIDIA",                      bio: "Built NVIDIA into the backbone of global AI infrastructure.",                           wiki: "Jensen_Huang",                      tier: 2 },
  { id: 14, name: "Jack Ma",              firm: "Alibaba Group",               bio: "Built China's largest e-commerce empire from a Hangzhou apartment.",                   wiki: "Jack_Ma",                           tier: 2 },
  { id: 15, name: "Masayoshi Son",        firm: "SoftBank",                    bio: "Japan's most prolific tech investor. Architect of the $100B Vision Fund.",              wiki: "Masayoshi_Son",                     tier: 2 },
  { id: 16, name: "Steve Cohen",          firm: "Point72",                     bio: "Billionaire trader who navigated a $1.8B SAC Capital settlement.",                     wiki: "Steve_Cohen_(businessman)",         tier: 2 },
  { id: 17, name: "Ken Griffin",          firm: "Citadel",                     bio: "Runs the world's most profitable hedge fund from Chicago.",                             wiki: "Kenneth_C._Griffin",                tier: 2 },
  { id: 18, name: "Carl Icahn",           firm: "Icahn Enterprises",           bio: "Legendary activist investor feared by corporate boards for decades.",                   wiki: "Carl_Icahn",                        tier: 2 },

  // ── TIER 3 ── Well-known finance figures ────────────────────────────────
  { id: 19, name: "Bill Ackman",          firm: "Pershing Square",             bio: "High-conviction activist investor known for bold, public bets.",                       wiki: "Bill_Ackman",                       tier: 3 },
  { id: 20, name: "Steve Mnuchin",        firm: "US Treasury / Dune Capital",  bio: "Former Goldman partner and US Treasury Secretary under Trump.",                       wiki: "Steven_Mnuchin",                    tier: 3 },
  { id: 21, name: "Paul Tudor Jones",     firm: "Tudor Investment Corp",       bio: "Predicted the 1987 crash. Pioneer of global macro trading.",                           wiki: "Paul_Tudor_Jones",                  tier: 3 },
  { id: 22, name: "David Tepper",         firm: "Appaloosa Management",        bio: "Made $7B buying bank stocks at 2009 crisis lows.",                                     wiki: "David_Tepper",                      tier: 3 },
  { id: 23, name: "Tom Steyer",           firm: "Farallon Capital",            bio: "Ran Farallon Capital's $20B hedge fund for two decades before pivoting to activism.", wiki: "Tom_Steyer",                        tier: 3 },
  { id: 24, name: "Marc Andreessen",      firm: "Andreessen Horowitz",         bio: "Co-created the web browser. Now runs the top VC firm.",                                wiki: "Marc_Andreessen",                   tier: 3 },
  { id: 25, name: "Peter Thiel",          firm: "Founders Fund",               bio: "PayPal co-founder. First outside investor in Facebook.",                               wiki: "Peter_Thiel",                       tier: 3 },
  { id: 26, name: "Cathie Wood",          firm: "ARK Invest",                  bio: "Evangelist of disruptive innovation investing. Manages ARK ETFs.",                     wiki: "Cathie_Wood",                       tier: 3 },
  { id: 27, name: "Steve Schwarzman",     firm: "Blackstone",                  bio: "Built Blackstone into the world's largest alternative asset manager.",                 wiki: "Stephen_A._Schwarzman",             tier: 3 },
  { id: 28, name: "David Rubenstein",     firm: "The Carlyle Group",           bio: "Co-founded Carlyle, one of the world's largest private equity firms.",                 wiki: "David_Rubenstein",                  tier: 3 },
  { id: 29, name: "Henry Kravis",         firm: "KKR",                         bio: "Invented the leveraged buyout. KKR co-founder and PE pioneer.",                        wiki: "Henry_Kravis",                      tier: 3 },
  { id: 30, name: "Jim Simons",           firm: "Renaissance Technologies",    bio: "Mathematician who built the most successful hedge fund in history.",                   wiki: "Jim_Simons_(mathematician)",        tier: 3 },
  { id: 31, name: "Sam Altman",           firm: "OpenAI",                      bio: "CEO of OpenAI. The public face of the generative AI revolution.",                      wiki: "Sam_Altman",                        tier: 3 },
  { id: 32, name: "Patrick Collison",     firm: "Stripe",                      bio: "Co-founded Stripe, the most valuable private fintech company.",                        wiki: "Patrick_Collison",                  tier: 3 },
  { id: 33, name: "Jack Dorsey",          firm: "Block",                       bio: "Co-founded Twitter and Square/Block. Bitcoin maximalist.",                             wiki: "Jack_Dorsey",                       tier: 3 },

  // ── TIER 4 ── Major finance / well-known within industry ────────────────
  { id: 34, name: "Howard Marks",         firm: "Oaktree Capital",             bio: "Master of distressed debt. His investor memos are required reading.",                 wiki: "Howard_Marks_(investor)",           tier: 4 },
  { id: 35, name: "Eric Schmidt",         firm: "Google / Alphabet",           bio: "Google's CEO from 2001–2011. Guided its growth from startup to $100B company.",      wiki: "Eric_Schmidt",                      tier: 4 },
  { id: 36, name: "David Solomon",        firm: "Goldman Sachs",               bio: "CEO of Goldman Sachs. Also moonlights as a DJ.",                                      wiki: "David_M._Solomon",                  tier: 4 },
  { id: 37, name: "Jane Fraser",          firm: "Citigroup",                   bio: "First woman to lead a major Wall Street bank.",                                        wiki: "Jane_Fraser_(executive)",           tier: 4 },
  { id: 38, name: "Brian Moynihan",       firm: "Bank of America",             bio: "Rebuilt Bank of America's reputation after the 2008 financial crisis.",               wiki: "Brian_Moynihan",                    tier: 4 },
  { id: 39, name: "Michael Dell",         firm: "Dell Technologies",           bio: "Founded Dell at age 19. Took it private in 2013 and relisted it as a $50B+ company.", wiki: "Michael_Dell",                     tier: 4 },
  { id: 40, name: "Marc Rowan",           firm: "Apollo Global Management",    bio: "Took over Apollo from Leon Black. Built it into an insurance powerhouse.",            wiki: "Marc_Rowan",                        tier: 4 },
  { id: 41, name: "Larry Summers",        firm: "Harvard / US Treasury",       bio: "Former US Treasury Secretary and Harvard president. Top macro economic voice.",      wiki: "Lawrence_Summers",                  tier: 4 },
  { id: 42, name: "Abigail Johnson",      firm: "Fidelity Investments",        bio: "Third-generation CEO of Fidelity. Steered it into digital assets.",                  wiki: "Abigail_Johnson",                   tier: 4 },
  { id: 43, name: "Mike Novogratz",       firm: "Galaxy Digital",              bio: "Former Fortress macro fund manager turned crypto bull. Runs Galaxy Digital.",        wiki: "Mike_Novogratz",                    tier: 4 },
  { id: 44, name: "Chamath Palihapitiya", firm: "Social Capital",              bio: "Facebook's early growth VP. Became a prominent SPAC and tech investor.",             wiki: "Chamath_Palihapitiya",              tier: 4 },
  { id: 45, name: "Hank Paulson",         firm: "Goldman Sachs / US Treasury", bio: "Former Goldman Sachs CEO and US Treasury Secretary during the 2008 financial crisis.", wiki: "Henry_Paulson",                    tier: 4 },
  { id: 46, name: "Mohamed El-Erian",     firm: "Allianz",                     bio: "Former PIMCO CEO. Prolific commentator on global macro economics.",                   wiki: "Mohamed_El-Erian",                  tier: 4 },
  { id: 47, name: "John Doerr",           firm: "Kleiner Perkins",             bio: "Early backer of Google, Amazon, and Netscape. The most celebrated Silicon Valley VC.", wiki: "John_Doerr",                      tier: 4 },
  { id: 48, name: "Marc Benioff",         firm: "Salesforce",                  bio: "Founded Salesforce and pioneered the SaaS model. Built it into a $200B enterprise giant.", wiki: "Marc_Benioff",                 tier: 4 },
  { id: 49, name: "Michael Milken",       firm: "Milken Institute",            bio: "Invented junk bonds in the 1980s. Transformed corporate finance.",                   wiki: "Michael_Milken",                    tier: 4 },
  { id: 50, name: "Brian Armstrong",      firm: "Coinbase",                    bio: "Built America's largest crypto exchange from a seed investment.",                     wiki: "Brian_Armstrong_(businessman)",     tier: 4 },
  { id: 51, name: "Vlad Tenev",           firm: "Robinhood",                   bio: "Made zero-commission stock trading mainstream. Survived the meme stock era.",        wiki: "Vlad_Tenev",                        tier: 4 },
  { id: 52, name: "Lloyd Blankfein",      firm: "Goldman Sachs",               bio: "Led Goldman through the 2008 crisis. Famously said he was 'doing God's work.'",     wiki: "Lloyd_Blankfein",                   tier: 4 },
  { id: 53, name: "James Gorman",         firm: "Morgan Stanley",              bio: "Transformed Morgan Stanley into a wealth management powerhouse.",                    wiki: "James_P._Gorman",                   tier: 4 },

  // ── TIER 5 ── Finance / industry well-known ──────────────────────────────
  { id: 54, name: "Charlie Munger",       firm: "Berkshire Hathaway",          bio: "Warren Buffett's partner for 60 years. Shaped Berkshire's philosophy of buying quality businesses.", wiki: "Charlie_Munger",           tier: 5 },
  { id: 55, name: "John Bogle",           firm: "Vanguard",                    bio: "Founded Vanguard and invented the index fund. Changed investing forever.",            wiki: "John_Bogle",                        tier: 5 },
  { id: 56, name: "Chuck Schwab",         firm: "Charles Schwab",              bio: "Democratized stock brokerage with the discount broker model.",                       wiki: "Charles_R._Schwab",                 tier: 5 },
  { id: 57, name: "Mark Mobius",          firm: "Mobius Capital Partners",     bio: "Pioneer of emerging market investing for three decades at Franklin Templeton.",      wiki: "Mark_Mobius",                       tier: 5 },
  { id: 58, name: "Michael Lewis",        firm: "Author",                      bio: "Wrote Liar's Poker, The Big Short, and Flash Boys. Finance's greatest storyteller.", wiki: "Michael_Lewis_(author)",            tier: 5 },
  { id: 59, name: "Nassim Taleb",         firm: "Universa Investments",        bio: "Philosopher-trader. Wrote The Black Swan. Profited from the 2008 crash.",            wiki: "Nassim_Nicholas_Taleb",             tier: 5 },
  { id: 60, name: "Nouriel Roubini",      firm: "Roubini Macro Associates",    bio: "Predicted the 2008 crisis years in advance. Known as 'Dr. Doom'.",                   wiki: "Nouriel_Roubini",                   tier: 5 },
  { id: 61, name: "Larry Ellison",        firm: "Oracle",                      bio: "Co-founded Oracle and built it into the world's leading database and cloud company.", wiki: "Larry_Ellison",                    tier: 5 },
  { id: 62, name: "David Swensen",        firm: "Yale Endowment",              bio: "Pioneered the endowment model. Grew Yale's endowment from $1B to $40B.",             wiki: "David_Swensen",                     tier: 5 },
  { id: 63, name: "Sandy Weill",          firm: "Citigroup",                   bio: "Built Citigroup through mergers. Key architect of Glass-Steagall's repeal.",         wiki: "Sanford_Weill",                     tier: 5 },
  { id: 64, name: "Bob Iger",             firm: "Disney",                      bio: "Disney's transformational CEO. Oversaw the Marvel, Pixar, and Star Wars acquisitions.", wiki: "Bob_Iger",                         tier: 5 },
  { id: 65, name: "Kevin O'Leary",        firm: "O'Leary Ventures",            bio: "Shark Tank's Mr. Wonderful. Sold his software company for $3.7B.",                  wiki: "Kevin_O'Leary",                     tier: 5 },
  { id: 66, name: "Mark Cuban",           firm: "Dallas Mavericks",            bio: "Dot-com billionaire. Shark Tank star. Dallas Mavericks owner.",                      wiki: "Mark_Cuban",                        tier: 5 },
  { id: 67, name: "Dan Schulman",         firm: "PayPal",                      bio: "Led PayPal's decade of growth from 175M to 430M active accounts.",                   wiki: "Dan_Schulman",                      tier: 5 },
  { id: 68, name: "Tidjane Thiam",        firm: "Credit Suisse",               bio: "Former Credit Suisse CEO who restructured the bank before its 2023 collapse.",       wiki: "Tidjane_Thiam",                     tier: 5 },
  { id: 69, name: "Rob Arnott",           firm: "Research Affiliates",         bio: "Invented fundamental indexing. Challenges cap-weighted index funds.",                wiki: "Rob_Arnott",                        tier: 5 },
  { id: 70, name: "Walter Schloss",       firm: "WJS Partners",               bio: "Benjamin Graham's protégé. Ran WJS Partners for 47 years with 16% annual returns.", wiki: "Walter_Schloss",                    tier: 5 },
  { id: 71, name: "Mary Callahan Erdoes", firm: "JPMorgan Asset Management",   bio: "Runs JPMorgan's $3T asset and wealth management division.",                          wiki: "Mary_Callahan_Erdoes",              tier: 5 },
  { id: 72, name: "Bruce Flatt",          firm: "Brookfield Asset Management", bio: "Runs one of the world's largest alternative asset managers from Toronto.",           wiki: "Bruce_Flatt",                       tier: 5 },
  { id: 73, name: "Sergio Ermotti",       firm: "UBS",                         bio: "UBS CEO who returned to lead the emergency takeover of Credit Suisse.",              wiki: "Sergio_Ermotti",                    tier: 5 },
  { id: 74, name: "Jeffrey Sprecher",     firm: "ICE / NYSE",                  bio: "Founded Intercontinental Exchange and acquired the New York Stock Exchange.",        wiki: "Jeffrey_Sprecher",                  tier: 5 },
  { id: 75, name: "Gary Gensler",         firm: "SEC",                         bio: "Former SEC Chair. Goldman partner turned aggressive crypto regulator.",              wiki: "Gary_Gensler",                      tier: 5 },
  { id: 76, name: "Janet Yellen",         firm: "US Treasury",                 bio: "First woman to chair the Fed, then the first female Treasury Secretary.",            wiki: "Janet_Yellen",                      tier: 5 },
  { id: 77, name: "Jerome Powell",        firm: "Federal Reserve",             bio: "Fed Chair who navigated pandemic money printing and the inflation fight.",           wiki: "Jerome_Powell",                     tier: 5 },
  { id: 78, name: "Christine Lagarde",    firm: "European Central Bank",       bio: "ECB President. Former IMF chief. France's first female finance minister.",            wiki: "Christine_Lagarde",                 tier: 5 },
  { id: 79, name: "Ben Bernanke",         firm: "Federal Reserve",             bio: "Fed Chair who launched QE to prevent a second Great Depression in 2008.",            wiki: "Ben_Bernanke",                      tier: 5 },
  { id: 80, name: "Vikram Pandit",        firm: "Citigroup",                   bio: "Steered Citigroup through the 2008 crisis. Ran it on a $1 annual salary.",          wiki: "Vikram_Pandit",                     tier: 5 },

  // ── TIER 6 ── Deep finance / specialist ──────────────────────────────────
  { id: 81, name: "David Bonderman",      firm: "TPG Capital",                 bio: "Co-founded TPG, one of the world's largest private equity firms.",                  wiki: "David_Bonderman",                   tier: 6 },
  { id: 82, name: "Jim Breyer",           firm: "Breyer Capital",              bio: "Led Accel's early Facebook investment. One of Silicon Valley's top VCs.",            wiki: "Jim_Breyer",                        tier: 6 },
  { id: 83, name: "John Arnold",          firm: "Arnold Ventures",             bio: "Made $1B+ trading natural gas at Enron. Now a major philanthropist.",                wiki: "John_D._Arnold",                    tier: 6 },
  { id: 84, name: "Sam Zell",             firm: "Equity Group Investments",    bio: "Real estate billionaire known as the 'Grave Dancer'. Built a $40B+ empire.",       wiki: "Sam_Zell",                          tier: 6 },
  { id: 85, name: "Vinod Khosla",         firm: "Khosla Ventures",             bio: "Co-founded Sun Microsystems. Now runs Khosla Ventures, focused on moonshot clean-energy bets.", wiki: "Vinod_Khosla",              tier: 6 },
  { id: 86, name: "Robert Rubin",         firm: "Goldman Sachs / US Treasury", bio: "Co-chairman of Goldman Sachs and US Treasury Secretary under Clinton.",            wiki: "Robert_Rubin",                      tier: 6 },
  { id: 87, name: "Joshua Harris",        firm: "Apollo Global Management",    bio: "Apollo co-founder. Also owns the New Jersey Devils and Philadelphia 76ers.",        wiki: "Joshua_Harris_(businessman)",       tier: 6 },
  { id: 88, name: "Adena Friedman",       firm: "Nasdaq",                      bio: "First woman to lead a major US stock exchange as Nasdaq CEO.",                      wiki: "Adena_Friedman",                    tier: 6 },
  { id: 89, name: "Jes Staley",           firm: "Barclays",                    bio: "Former Barclays CEO. Left amid controversy over Jeffrey Epstein connections.",       wiki: "Jes_Staley",                        tier: 6 },
  { id: 90, name: "Seth Klarman",         firm: "Baupost Group",               bio: "Runs the secretive $30B Baupost Group. Author of the rare value classic Margin of Safety.", wiki: "Seth_Klarman",              tier: 6 },
  { id: 91, name: "Brian Chesky",         firm: "Airbnb",                      bio: "Co-founded Airbnb and grew it from an air mattress startup into a $90B company.",   wiki: "Brian_Chesky",                      tier: 6 },
  { id: 92, name: "Orlando Bravo",        firm: "Thoma Bravo",                 bio: "Runs Thoma Bravo, the most aggressive PE buyer of software companies.",             wiki: "Orlando_Bravo",                     tier: 6 },
  { id: 93, name: "Paul Volcker",         firm: "Federal Reserve",             bio: "Fed Chair who killed 1970s inflation with brutal rate hikes. A Wall Street legend.", wiki: "Paul_Volcker",                     tier: 6 },
  { id: 94, name: "Chris Hohn",           firm: "TCI Fund Management",         bio: "Runs TCI, one of the world's best long-term performing activist hedge funds.",      wiki: "Christopher_Hohn",                  tier: 6 },
  { id: 95, name: "Nicolai Tangen",       firm: "Norges Bank Investment Mgmt", bio: "Manages Norway's $1.7T sovereign wealth fund, the world's largest.",              wiki: "Nicolai_Tangen",                    tier: 6 },
  { id: 96, name: "Prem Watsa",           firm: "Fairfax Financial",           bio: "Canada's Warren Buffett. Runs Fairfax Financial Holdings.",                        wiki: "Prem_Watsa",                        tier: 6 },
  { id: 97, name: "Scott Bessent",        firm: "Key Square / US Treasury",    bio: "Former Soros CIO turned macro fund manager. Current US Treasury Secretary.",       wiki: "Scott_Bessent",                     tier: 6 },
  { id: 98, name: "Michael Arougheti",    firm: "Ares Management",             bio: "Co-founded Ares Management, a leading alternative credit and PE manager.",         wiki: "Michael_Arougheti",                 tier: 6 },
  { id: 99, name: "Anthony Scaramucci",   firm: "SkyBridge Capital",           bio: "Founder of SkyBridge Capital. Known for his brief White House stint and media presence.", wiki: "Anthony_Scaramucci",             tier: 6 },
  { id: 100, name: "Tom Barrack",         firm: "Colony Capital",              bio: "Founder of Colony Capital. Real estate PE pioneer and former Trump advisor.",      wiki: "Tom_Barrack",                       tier: 6 },
];
